#!/usr/bin/perl
# paperboy
use strict;

my $database = "$ENV{HOME}/.arbete";

if(!-e $database) {
  open(my $fh, '>', $database);
  close $fh;
}

sub addRecord {
  print "Distrikt: ";
  chomp(my $district = <STDIN>);
  print "Väntetid: ";
  chomp(my $wait = <STDIN>);
  print "Tidsåtgång: ";
  chomp(my $time = <STDIN>);
  print "Anteckningar: ";
  chomp(my $notes = <STDIN>);
  print "Övertid: ";
  chomp(my $overtime = <STDIN>);
  print "\n";
  my @time = localtime(time);
  my @months = qw(Januari
                 Februari
                 Mars
                 April
                 Maj
                 Juni
                 Juli
                 Augusti
                 September
                 Oktober
                 Novemer
                 December
                 );

  chomp(my $date = sprintf("%02s:%02s:%02s %02s %s %s\n",
    $time[2], $time[1], $time[0], 
    $time[3], $months[$time[4]], $time[5]+=1900));

  my $fh;
  open($fh, '>>', $database) or die "Can not open $database: $!";
  print $fh "Datum: $date\n";
  print $fh "Distrikt: $district\n";
  print $fh "Tidsåtgång: $time minuter\n";
  print $fh "Väntetid: $wait minuter (@{[convWait($wait)]} perioder)\n" 
    unless !$wait;
  print $fh "Anteckningar: $notes\n"
    unless !$notes;
  print $fh "--\n";
}

addRecord;
sub convWait {
  my $time = shift;
  $time-=10;
  $time = $time/10; #
  use POSIX;
  $time = ceil($time);
  if($time < 1) {
    return;
  }
  return $time;       # eller så kunde man skitit i $time-=10;
                      # och avrundat nedåt istället, men POSIX är kul
}
